"""Final

Revision ID: 1919d2a5d610
Revises: 4cbf67ef67ae
Create Date: 2025-12-18 19:07:45.322023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1919d2a5d610'
down_revision: Union[str, Sequence[str], None] = '4cbf67ef67ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleep_logs', 'sleep_day',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sleep_logs', 'sleep_day',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
