"""Final v2

Revision ID: 1c6f0e5b4335
Revises: 1919d2a5d610
Create Date: 2025-12-26 03:09:40.592739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6f0e5b4335'
down_revision: Union[str, Sequence[str], None] = '1919d2a5d610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_connections', sa.Column('device_identifier', sa.String(), nullable=True))
    op.add_column('device_connections', sa.Column('device_name', sa.String(), nullable=True))
    op.add_column('device_connections', sa.Column('device_type', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'device_connections', ['device_identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_connections', type_='unique')
    op.drop_column('device_connections', 'device_type')
    op.drop_column('device_connections', 'device_name')
    op.drop_column('device_connections', 'device_identifier')
    # ### end Alembic commands ###
