"""Device connection v1

Revision ID: 250b216eb571
Revises: 72d90c562f2b
Create Date: 2025-12-10 17:50:02.405980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '250b216eb571'
down_revision: Union[str, Sequence[str], None] = '72d90c562f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_connections', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('device_connections', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_device_connections_device_id'), 'device_connections', ['device_id'], unique=False)
    op.drop_column('vital_signs', 'battery')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('battery', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_device_connections_device_id'), table_name='device_connections')
    op.alter_column('device_connections', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_connections', 'last_seen',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('device_connections', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
