"""Final v2 stress editing

Revision ID: 3987a00aa8cf
Revises: 75095c149d0c
Create Date: 2025-12-27 00:50:10.336736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3987a00aa8cf'
down_revision: Union[str, Sequence[str], None] = '75095c149d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('stress', sa.String(), nullable=True))
    op.drop_column('vital_signs', 'breathing_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('breathing_rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('vital_signs', 'stress')
    # ### end Alembic commands ###
