"""Final v2 vitals  editing

Revision ID: 3a986f92bbb9
Revises: 3987a00aa8cf
Create Date: 2025-12-27 01:00:22.540006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a986f92bbb9'
down_revision: Union[str, Sequence[str], None] = '3987a00aa8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('hr', sa.Integer(), nullable=True))
    op.add_column('vital_signs', sa.Column('temp', sa.Float(), nullable=True))
    op.drop_column('vital_signs', 'blood_pressure_diastolic')
    op.drop_column('vital_signs', 'blood_pressure_systolic')
    op.drop_column('vital_signs', 'heart_rate')
    op.drop_column('vital_signs', 'temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('heart_rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('blood_pressure_systolic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vital_signs', sa.Column('blood_pressure_diastolic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('vital_signs', 'temp')
    op.drop_column('vital_signs', 'hr')
    # ### end Alembic commands ###
