"""add deep sleep hours v2

Revision ID: 583f9b45e682
Revises: 7d4bef85096d
Create Date: 2025-12-13 03:22:21.135314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583f9b45e682'
down_revision: Union[str, Sequence[str], None] = '7d4bef85096d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sleep_logs', sa.Column('rem_sleep_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sleep_logs', 'rem_sleep_hours')
    # ### end Alembic commands ###
