"""Vital_signs v2

Revision ID: 72d90c562f2b
Revises: d7f4e2bbfa62
Create Date: 2025-12-09 19:05:52.427014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d90c562f2b'
down_revision: Union[str, Sequence[str], None] = 'd7f4e2bbfa62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('breathing_rate', sa.Integer(), nullable=True))
    op.drop_column('vital_signs', 'respiratory_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_signs', sa.Column('respiratory_rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('vital_signs', 'breathing_rate')
    # ### end Alembic commands ###
