"""add deep sleep hours

Revision ID: 7d4bef85096d
Revises: 250b216eb571
Create Date: 2025-12-13 03:19:25.089043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d4bef85096d'
down_revision: Union[str, Sequence[str], None] = '250b216eb571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Tables activity_daily and activity_weekly have been removed, skip these operations
    # op.alter_column('activity_daily', 'user_id', ...)
    # op.alter_column('activity_daily', 'created_at', ...)
    # op.drop_constraint('activity_daily_user_id_activity_date_key', 'activity_daily', type_='unique')
    # op.alter_column('activity_weekly', 'user_id', ...)
    # op.alter_column('activity_weekly', 'created_at', ...)
    # op.drop_constraint('activity_weekly_user_id_year_week_key', 'activity_weekly', type_='unique')
    op.add_column('sleep_logs', sa.Column('deep_sleep_hours', sa.Float(), nullable=True))
    op.add_column('sleep_logs', sa.Column('light_sleep_hours', sa.Float(), nullable=True))
    op.add_column('sleep_logs', sa.Column('awake_minutes', sa.Integer(), nullable=True))
    op.alter_column('sleep_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sleep_logs', 'sleep_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sleep_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('sleep_logs_user_id_sleep_date_key'), 'sleep_logs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sleep_logs_user_id_sleep_date_key'), 'sleep_logs', ['user_id', 'sleep_date'], postgresql_nulls_not_distinct=False)
    op.alter_column('sleep_logs', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sleep_logs', 'sleep_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sleep_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sleep_logs', 'awake_minutes')
    op.drop_column('sleep_logs', 'light_sleep_hours')
    op.drop_column('sleep_logs', 'deep_sleep_hours')
    # Tables activity_daily and activity_weekly have been removed, skip these operations
    # op.create_unique_constraint('activity_weekly_user_id_year_week_key', 'activity_weekly', ...)
    # op.alter_column('activity_weekly', 'created_at', ...)
    # op.alter_column('activity_weekly', 'user_id', ...)
    # op.create_unique_constraint('activity_daily_user_id_activity_date_key', 'activity_daily', ...)
    # op.alter_column('activity_daily', 'created_at', ...)
    # op.alter_column('activity_daily', 'user_id', ...)
    # ### end Alembic commands ###
