"""add verification_code to users

Revision ID: 81b91e67f8a4
Revises: 
Create Date: 2025-12-04 17:54:49.486678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b91e67f8a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'users', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_column('users', 'verification_code')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    # ### end Alembic commands ###
