"""add_fall_detections_table

Revision ID: d2fb4a274da9
Revises: 446c28ca23c1
Create Date: 2026-01-02 15:54:50.958010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fb4a274da9'
down_revision: Union[str, Sequence[str], None] = '446c28ca23c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fall_detections',
    sa.Column('fall_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fall_id')
    )
    op.create_index(op.f('ix_fall_detections_fall_id'), 'fall_detections', ['fall_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fall_detections_fall_id'), table_name='fall_detections')
    op.drop_table('fall_detections')
    # ### end Alembic commands ###
