"""Vital_signs v1

Revision ID: d7f4e2bbfa62
Revises: dc8f4619869a
Create Date: 2025-12-09 17:48:31.895675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f4e2bbfa62'
down_revision: Union[str, Sequence[str], None] = 'dc8f4619869a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vital_signs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_vital_signs_vital_id'), 'vital_signs', ['vital_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vital_signs_vital_id'), table_name='vital_signs')
    op.alter_column('vital_signs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
